name: 徐强明
author: 徐强明
baseurl: 
description: 枕上诗书闲处好
github: http://www.github.com/xuqiangm
#twitter: http://www.twitter.com/
facebook: http://www.facebook.com
linkedin: http://www.linkedin.com
email: xuqiangm@gmail.com
location: 32°2'38"N   118°46'43"E
#disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.
encoding: utf-8

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
